#!/usr/bin/env node
/**
 * Generates frontend/lib/abis.ts from Foundry's compiled artifacts in out/.
 *
 * Run from the repo root (the folder containing src/, lib/, out/, frontend/),
 * AFTER running `forge build`:
 *   forge build
 *   node frontend/scripts/gen-abis.js
 *
 * This reads ABIs directly from Foundry's own build output — no separate
 * Solidity compilation happens in this script, so it's fast (the slow part,
 * actually compiling the contracts, was already done by `forge build`,
 * which uses the same native compiler as `forge test`).
 *
 * Re-run any time a contract's external interface changes:
 *   forge build && node frontend/scripts/gen-abis.js
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..", ".."); // frontend/scripts -> repo root
const FRONTEND = path.join(ROOT, "frontend");
const OUT_DIR = path.join(ROOT, "out");

if (!fs.existsSync(OUT_DIR)) {
  console.error(
    `Could not find ${OUT_DIR}.\n` +
      "Run `forge build` from the repo root first, then re-run this script.\n"
  );
  process.exit(1);
}

// Contract name -> source file name (the .sol file it's defined in).
// This is the v1 frontend scope: trading, orders, stop-loss, LP vault,
// rewards, liquidation, the router, and the ERC20s used as collateral/reward.
const targets = {
  MarginManager: "MarginManager.sol",
  PriceFeed: "PriceFeed.sol",
  OracleAggregator: "OracleAggregator.sol",
  Vault: "Vault.sol",
  CollateralVault: "CollateralVault.sol",
  LeverageController: "LeverageController.sol",
  FundingRateEngine: "FundingRateEngine.sol",
  RiskManager: "RiskManager.sol",
  OrderBook: "OrderBook.sol",
  StopLossManager: "StopLossManager.sol",
  LPVault: "LPVault.sol",
  RewardDistributor: "RewardDistributor.sol",
  LiquidationEngine: "LiquidationEngine.sol",
  PositionRouter: "PositionRouter.sol",
  MockERC20: "MockERC20.sol",
  InsuranceFund: "InsuranceFund.sol",
  StrategyVault: "StrategyVault.sol",
  StrategyFactory: "StrategyFactory.sol",
  StrategyRegistry: "StrategyRegistry.sol",
};

/**
 * Foundry's default layout is out/<SourceFile>.sol/<ContractName>.json.
 * If a contract isn't found there (e.g. project uses a flatter out/ layout,
 * or the source file lives in a subfolder Foundry mirrors differently),
 * fall back to a recursive search by filename across all of out/.
 */
function findArtifact(contractName, sourceFileName) {
  const direct = path.join(OUT_DIR, sourceFileName, `${contractName}.json`);
  if (fs.existsSync(direct)) return direct;

  // Fallback: search recursively for <ContractName>.json anywhere in out/
  const stack = [OUT_DIR];
  while (stack.length > 0) {
    const dir = stack.pop();
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (entry.name === `${contractName}.json`) {
        return full;
      }
    }
  }
  return null;
}

let ts =
  "// Auto-generated by frontend/scripts/gen-abis.js — do not edit by hand.\n" +
  "// Regenerate after any contract interface change:\n" +
  "//   forge build && node frontend/scripts/gen-abis.js\n\n";

let missing = [];

for (const [name, sourceFile] of Object.entries(targets)) {
  const artifactPath = findArtifact(name, sourceFile);
  if (!artifactPath) {
    missing.push(name);
    continue;
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  if (!artifact.abi) {
    console.error(`Artifact for ${name} at ${artifactPath} has no "abi" field.`);
    missing.push(name);
    continue;
  }
  ts += `export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
  console.log(`  ✓ ${name} (${artifact.abi.length} ABI entries)`);
}

if (missing.length > 0) {
  console.error(
    `\nCould not find compiled artifacts for: ${missing.join(", ")}\n` +
      "Make sure `forge build` ran successfully and these contracts exist in src/.\n"
  );
  process.exit(1);
}

const outPath = path.join(FRONTEND, "lib", "abis.ts");
fs.writeFileSync(outPath, ts);
console.log(`\nWrote ${outPath} — ${Object.keys(targets).length} ABIs, ${ts.split("\n").length} lines`);